# Dependency repositories
nexusPublicRepository=https://nexus-ci.delta.sbrf.ru/repository/public/
nexusInternalRepository=https://nexus-ci.delta.sbrf.ru/repository/maven-lib-int/
nexusInternalReleaseRepository=https://nexus-ci.delta.sbrf.ru/repository/maven-lib-release/
nexusInternalDevRepository=https://nexus-ci.delta.sbrf.ru/repository/maven-lib-dev/

# Credentials are loaded from ~/.gradle/gradle.properties, -PtokenName/-PtokenPassword, or ignored gradle.local.properties.


#логин-пароли к Nexus

# Gradle properties
org.gradle.parallel=true
org.gradle.jvmargs='-Dfile.encoding=UTF-8'
org.gradle.daemon=false
# If you get watch directory error in console, disable this setting
org.gradle.vfs.watch=false

# Dependencies versions
# Platform V AT Framework
perfeccionistaVersion=0.9.4-Beta
platformvatframeworkVersion=1.10.3-beta
allureVersion = 2.29.0
cucumberVersion = 7.21.0
jnaVersion = 5.17.0
junit5Version = 5.10.3
junitPlatformSuiteVersion = 1.9.1
queryVersion = 13.5.0

# Library
javaxAnnotationVersion=1.3.2
slf4jVersion=2.0.16
awaitilityVersion=4.2.1
mockitoVersion = 5.2.0
