package util.ignite;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.concurrent.CountDownLatch;
import java.util.regex.Pattern;

/** Standalone JDK-only child used by transport tests; no Ignite, Jackson, JUnit or network access. */
public final class IgniteSessionProtocolFixture {
    private static final String PREFIX = "IGNITE_SESSION=";
    private static final Pattern PROTOCOL = Pattern.compile("\"protocol\"\\s*:\\s*1(?=\\s*[,}])");

    private IgniteSessionProtocolFixture() { }

    public static void main(String[] args) throws Exception {
        if (args.length != 2) throw new IllegalArgumentException("Expected scenario and PID file");
        String scenario = args[0];
        Path pidFile = Path.of(args[1]);
        long pid = ProcessHandle.current().pid();
        Files.writeString(pidFile, Long.toString(pid), StandardCharsets.UTF_8);
        if (scenario.equals("protocol-mismatch")) {
            reply(2, "ready", "\"ok\":true,\"result\":{\"state\":\"ready\",\"pid\":" + pid + "}");
            waitForTermination();
            return;
        }
        reply(1, "ready", "\"ok\":true,\"result\":{\"state\":\"ready\",\"pid\":" + pid
                + ",\"sessionId\":\"fake-session\"}");
        int operations = 0;
        try (var input = new BufferedReader(new InputStreamReader(System.in, StandardCharsets.UTF_8))) {
            String line;
            while ((line = input.readLine()) != null) {
                if (!PROTOCOL.matcher(line).find()) throw new IllegalArgumentException("Expected protocol v1 command");
                String id = field(line, "id");
                String mode = field(line, "mode");
                if (mode.equals("close")) {
                    Files.writeString(pidFile.resolveSibling("closed.txt"), Integer.toString(operations), StandardCharsets.UTF_8);
                    reply(1, id, "\"ok\":true,\"result\":{\"state\":\"closed\",\"pid\":" + pid + "}");
                    return;
                }
                operations++;
                Files.writeString(pidFile.resolveSibling("command-received.txt"), mode, StandardCharsets.UTF_8);
                if (scenario.equals("timeout")) {
                    waitForTermination();
                    return;
                }
                if (scenario.equals("eof")) {
                    // Keep the process alive after EOF: the parent must terminate it before returning.
                    System.out.close();
                    System.err.close();
                    waitForTermination();
                    return;
                }
                if (scenario.equals("bad-id")) {
                    reply(1, "not-the-request-id", "\"ok\":true,\"result\":{}");
                    waitForTermination();
                    return;
                }
                if (mode.equals("verify")) {
                    reply(1, id, "\"ok\":false,\"errorType\":\"fixture.VerifyFailure\"");
                } else {
                    reply(1, id, "\"ok\":true,\"result\":{\"pid\":" + pid + ",\"mode\":\"" + mode
                            + "\",\"ordinal\":" + operations + ",\"sessionId\":\"fake-session\"}");
                }
            }
        }
    }

    /** Only the ASCII id/mode fields generated by IgniteHelperSession are needed here. */
    private static String field(String json, String name) {
        var matcher = Pattern.compile("\"" + name + "\"\\s*:\\s*\"([A-Za-z0-9-]+)\"").matcher(json);
        if (!matcher.find()) throw new IllegalArgumentException("Missing command field: " + name);
        return matcher.group(1);
    }

    private static void reply(int protocol, String id, String body) {
        System.out.println(PREFIX + "{\"protocol\":" + protocol + ",\"id\":\"" + id + "\"," + body + "}");
        System.out.flush();
    }

    private static void waitForTermination() throws InterruptedException {
        new CountDownLatch(1).await();
    }
}
